DROP ALL OBJECTS DELETE FILES;
create table IF NOT EXISTS mpas
(
    mpas_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpas_name CHARACTER VARYING(10) CHECK (mpas_name <> '') not null UNIQUE
);

create table IF NOT EXISTS genres
(
    genre_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name CHARACTER VARYING(50)  CHECK (genre_name <>'') NOT NULL UNIQUE
);

create table IF NOT EXISTS films
(
    film_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name        CHARACTER VARYING(100) CHECK (film_name <> '') not null,
    film_description CHARACTER VARYING(255),
    release_date     DATE NOT NULL,
    film_duration    INTEGER CHECK (film_duration > 0) NOT NULL,
    film_genre_id    INTEGER    REFERENCES GENRES (genre_id) ON DELETE SET NULL,
    mpa_id           INTEGER    REFERENCES MPAS (mpas_id) ON DELETE SET NULL
);

create table IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    CHARACTER VARYING(50)  CHECK (login <> '') NOT NULL UNIQUE,
    name     CHARACTER VARYING(50),
    email    CHARACTER VARYING(100) NOT NULL UNIQUE,
    birthday DATE
);

create table IF NOT EXISTS friends
(
    from_user   INTEGER    REFERENCES USERS (user_id) ON DELETE CASCADE,
    to_user     INTEGER    REFERENCES USERS (user_id) ON DELETE CASCADE,
    status      CHARACTER VARYING(20) DEFAULT 'Waiting',
    PRIMARY KEY (from_user, to_user)
);

create table IF NOT EXISTS likes
(
    user_id INTEGER REFERENCES USERS (user_id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES FILMS (film_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  INTEGER REFERENCES FILMS (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES GENRES (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);